---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "otelcollector.fullname" . }}-configmap
  annotations:
    # Support for k14s.io. This annotation will produce a redeployment when the configmap changes.
    kapp.k14s.io/versioned: ""
  labels:
    {{- include "otelcollector.labels" . | nindent 4 }}
data:
  m3dbDefaultStoragePolicy: "{{ .Values.configuration.m3dbDefaultStoragePolicy }}"
  m3dbDefaultMetricType: "{{ .Values.configuration.m3dbDefaultMetricsType }}"

