---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "clickhouse.fullname" . }}
  annotations:
    # Support for k14s.io. This annotation will produce a redeployment when the secret changes.
    kapp.k14s.io/versioned: ""
  labels:
    {{- include "clickhouse.labels" . | nindent 4 }}
data:
  username: {{ .Values.configuration.auth.username | b64enc | quote }}
  password: {{ .Values.configuration.auth.password | b64enc | quote }}
  database: {{ .Values.configuration.database | b64enc | quote }}
