---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "keycloak.fullname" . }}-configmap
  annotations:
    # Support for k14s.io. This annotation will produce a redeployment when the configmap changes.
    kapp.k14s.io/versioned: ""
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
data:
  db: "postgres"
  schema: "{{ .Values.global.keycloak.databaseSchema }}"
  host: "{{ include "postgresql.fullname" . }}"
  database: "{{ .Values.global.keycloak.database }}"

