name: Publish Helm Chart
run-name: Publish ${{ inputs.name }} Helm Chart with version ${{ inputs.tag }}
on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Name of the chart to release'
        required: true
      tag:
        description: 'Tag to release'
        required: true
        type: string

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  publish-chart:
    if: github.ref_name == github.event.repository.default_branch
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Container registry
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Log in to Github Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish Chart
        if: inputs.name == 'cosmo-chart'
        working-directory: helm
        run: |
          VERSION=${{ inputs.tag }} make publish-cosmo-chart

      - name: Publish Chart
        if: inputs.name == 'router-chart'
        working-directory: helm
        run: |
          VERSION=${{ inputs.tag }} make publish-router-chart
