name: Publish Helm Chart
run-name: Publish ${{ inputs.name }} Helm Chart
on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Name of the chart to release'
        required: true
        type: choice
        options:
          - cosmo-umbrella
          - router

env:
  REGISTRY: ghcr.io

jobs:
  publish-chart:
    if: github.ref_name == github.event.repository.default_branch
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Helm version
        run: helm version

      - name: yq - portable yaml processor
        uses: mikefarah/yq@v4.42.1

      - name: Log in with Helm to Container registry
        run: gh auth token | helm registry login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Publish Chart
        if: inputs.name == 'cosmo-umbrella'
        working-directory: helm
        run: |
          make publish-cosmo-chart VERSION=$(yq '.version' ./cosmo/Chart.yaml)

      - name: Publish Chart
        if: inputs.name == 'router'
        working-directory: helm
        run: |
          make publish-router-chart VERSION=$(yq '.version' ./cosmo/charts/router/Chart.yaml)
