---
name: Helm Release
run-name: helm-release

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: read
  pull-requests: write
  packages: write

env:
  CI: true
  REGISTRY: ghcr.io
  RELEASE_BRANCH: main

jobs:
  build_test:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - uses: googleapis/release-please-action@v4
        id: release
        with:
          # https://github.com/googleapis/release-please-action/issues/741
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json
          target-branch: ${{ env.RELEASE_BRANCH }}
          token: ${{ secrets.GH_TOKEN_HELM_RELEASES }}

      - uses: ./.github/actions/helm-release
        if: ${{ steps.release.outputs['helm/cosmo--release_created'] }}
        with:
          working-directory: ./helm
          registry: ${{ env.REGISTRY }}
          registry-username: ${{ github.actor }}
          registry-password: ${{ secrets.GITHUB_TOKEN }}
          make-target: publish-cosmo-chart

      - uses: ./.github/actions/helm-release
        if: ${{ steps.release.outputs['helm/cosmo/charts/router--release_created'] }}
        with:
          working-directory: ./helm
          registry: ${{ env.REGISTRY }}
          registry-username: ${{ github.actor }}
          registry-password: ${{ secrets.GITHUB_TOKEN }}
          make-target: publish-router-chart

      - uses: ./.github/actions/terraform-provider-cosmo-release
        if: ${{ steps.release.outputs['terraform-provider-cosmo--release_created'] }}
        with:
          working-directory: ./terraform-provider-cosmo
          gpg-private-key: ${{ secrets.TERRAFORM_PROVIDER_GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.TERRAFORM_PROVIDER_GPG_PASSPHRASE }}
          go-release-token: ${{ secrets.GITHUB_TOKEN }}
          release-tag: ${{ steps.release.outputs['terraform-provider-cosmo--tag_name'] }}
