---
name: helm-prepare-release
run-name: helm-prepare-release

on:
  workflow_dispatch:
  push:
    branches:
      - andi/eng-5520-automate-helm-chart-releases

permissions:
  contents: write
  pull-requests: write

env:
  CI: true
  REGISTRY: ghcr.io
  RELEASE_BRANCH: andi/helm-release-testing

jobs:
  prepare-release:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - uses: googleapis/release-please-action@v4
        id: release
        with:
          # https://github.com/googleapis/release-please-action/issues/741
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json
          target-branch: ${{ env.RELEASE_BRANCH }}
          token: ${{ secrets.GITHUB_TOKEN }}
          skip-github-release: false
          skip-github-pull-request: false

      - name: is-release-created
        if: ${{ steps.release.outputs.releases_created }}
        run: |
          echo "performing release"

      - name: show-release-output
        run: |
          echo "${{ steps.release.outputs.releases_created }}"
          echo "${{ steps.release.outputs.release_created }}"
          echo "${{ steps.release.outputs['helm/cosmo--release_created'] }}"
          echo "${{ steps.release.outputs['helm/cosmo/charts/router--tag_name'] }}"
          echo "${{ steps.release.outputs }}"
