---
name: release-helm-charts
run-name: package-helm-charts-release

on:
  workflow_dispatch:

permissions:
  contents: write
  packages: write
  pull-requests: write

env:
  CI: true
  REGISTRY: ghcr.io
  RELEASE_BRANCH: andi/helm-release-testing

jobs:
  publish-chart:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Log in to Github Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish Cosmo Chart
        working-directory: helm
        run: |
          make publish-cosmo-chart

      - name: Publish Router Chart
        working-directory: helm
        run: |
          make publish-router-chart
