name: Publish Helm Chart
run-name: Publish ${{ inputs.name }} Helm Chart
on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Name of the chart to release'
        required: true
        type: choice
        options:
          - cosmo-umbrella
          - router

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  publish-chart:
    if: github.ref_name == github.event.repository.default_branch
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Github Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish Chart
        if: inputs.name == 'cosmo-umbrella'
        working-directory: helm
        run: |
          VERSION=$(yq '.version' ./cosmo/Chart.yaml) make publish-cosmo-chart

      - name: Publish Chart
        if: inputs.name == 'router'
        working-directory: helm
        run: |
          VERSION=$(yq '.version' ./cosmo/charts/router/Chart.yaml) make publish-router-chart

      - name: Update docs
        working-directory: helm
        run: |
          make docs
