name: Release

on:
  workflow_dispatch:

concurrency:
  group: ${{github.workflow}}-${{github.head_ref}}
  cancel-in-progress: false

env:
  CI: true

jobs:
  stable-version:
    # https://docs.npmjs.com/generating-provenance-statements#publishing-packages-with-provenance-via-github-actions
    permissions:
      id-token: write
    timeout-minutes: 20
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_TOKEN_WORKFLOW_PUBLISH }}
      - uses: ./.github/actions/node
        with:
          working-directory: ${{ env.WORKING_DIRECTORY }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - run: npm config set //registry.npmjs.org/:_authToken $NPM_TOKEN
        shell: bash
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Install
        run: pnpm install

      - name: Build
        run: pnpm build

      - name: Publish packages & Create Github Releases
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          pnpm release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN_WORKFLOW_PUBLISH }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
