name: Release

on:
  workflow_dispatch:

concurrency:
  group: Production
  cancel-in-progress: false

env:
  CI: true

jobs:
  stable-version:
    # https://docs.npmjs.com/generating-provenance-statements#publishing-packages-with-provenance-via-github-actions
    permissions:
      id-token: write
    timeout-minutes: 20
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_TOKEN_WORKFLOW_PUBLISH }}

      - uses: ./.github/actions/node
        with:
          working-directory: ${{ env.WORKING_DIRECTORY }}

      - run: npm config set //registry.npmjs.org/:_authToken $NPM_TOKEN
        shell: bash
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Install
        run: |
          git tag controlplane@0.0.4
          git push origin --tags
          git tag router@0.0.4
          git push origin --tags
          git tag studio@0.0.4
          git push origin --tags
          git tag keycloak@0.0.4
          git push origin --tags
          git tag otelcollector@0.0.4
          git push origin --tags
