name: Release

on:
  workflow_dispatch:

concurrency:
  group: Production
  cancel-in-progress: false

env:
  CI: true

jobs:
  stable-version:
    # https://docs.npmjs.com/generating-provenance-statements#publishing-packages-with-provenance-via-github-actions
    permissions:
      id-token: write
    timeout-minutes: 20
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_TOKEN_WORKFLOW_PUBLISH }}

      - name: Install
        run: | 
          git tag controlplane@0.0.4
          git push origin --tags
