name: Test CI

on:
  push:
    branches: 
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: hoverkraft-tech/compose-action@v0.0.0
        with:
          compose-file: "docker-compose.full.yml"
          up-flags: "--build --remove-orphans --detach"
          down-flags: ""
          compose-flags: "--profile default"

      - name: Execute tests in the running services
        run: |
          ./scripts/setup-fulldemo.sh